{% set name = "codeguru_profiler_agent" %}
{% set version = "1.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/amazon-codeguru-profiler-python-agent/archive/v{{ version }}.tar.gz
  sha256: bec8feb92f2d5d2594bbf90197dcce093d3c4f37463ddd5612a006755e20e9ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3 >=1.14.0
    - python >=3.6

test:
  imports:
    - codeguru_profiler_agent
    - codeguru_profiler_agent.agent_metadata
  commands:
    - pip check
    - pytest --ignore=test/integration/
    # Skipped due to required credentials
    # See https://github.com/aws/amazon-codeguru-profiler-python-agent/tree/main/test/integration
  requires:
    - httpretty
    - mock
    - pip
    - pympler
    - pytest
  source_files:
    - test

about:
  home: https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html
  summary: The Python agent to be used for Amazon CodeGuru Profiler
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html
  dev_url: https://github.com/aws/amazon-codeguru-profiler-python-agent

extra:
  recipe-maintainers:
    - BastianZim
